<a href="https://colab.research.google.com/github/elmhrkshy/PyTorchTutorial/blob/main/PyTorchTutorialSrihariSir.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy

In [3]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [12]:
x = torch.zeros(5,3)
print(x)
y = torch.ones(4,5)
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [7]:
x = torch.rand(2,3)
y = torch.rand(3,3)
print(x)
print(y)

tensor([[0.2378, 0.2373, 0.6761],
        [0.3793, 0.7772, 0.5487]])
tensor([[0.8424, 0.8176, 0.4455],
        [0.5941, 0.1175, 0.8195],
        [0.0471, 0.1266, 0.1120]])


In [30]:
x = torch.randn(4,4)
print(x)
y = torch.randn(4,4)
#print(y)
z = torch.add(x,y)
#print(z)

tensor([[-1.3539, -0.2837, -1.8016,  1.5120],
        [ 0.7479,  0.8095, -1.2800, -1.4071],
        [ 1.7679, -1.7466, -0.9898, -0.0154],
        [ 1.2572, -0.0746, -1.7554,  0.5165]])


In [34]:
print(x[2,:])
print(x[2,:])

tensor([ 1.7679, -1.7466, -0.9898, -0.0154])
tensor([ 1.7679, -1.7466, -0.9898, -0.0154])


In [41]:
print(x)
y = x.view(16)
print(y)
print(y.size())
z = x.view(8,-1)
print(z)
print(z.size())
z = x.view(-1,4,1)
print(z)
print(z.size())

tensor([[-1.3539, -0.2837, -1.8016,  1.5120],
        [ 0.7479,  0.8095, -1.2800, -1.4071],
        [ 1.7679, -1.7466, -0.9898, -0.0154],
        [ 1.2572, -0.0746, -1.7554,  0.5165]])
tensor([-1.3539, -0.2837, -1.8016,  1.5120,  0.7479,  0.8095, -1.2800, -1.4071,
         1.7679, -1.7466, -0.9898, -0.0154,  1.2572, -0.0746, -1.7554,  0.5165])
torch.Size([16])
tensor([[-1.3539, -0.2837],
        [-1.8016,  1.5120],
        [ 0.7479,  0.8095],
        [-1.2800, -1.4071],
        [ 1.7679, -1.7466],
        [-0.9898, -0.0154],
        [ 1.2572, -0.0746],
        [-1.7554,  0.5165]])
torch.Size([8, 2])
tensor([[[-1.3539],
         [-0.2837],
         [-1.8016],
         [ 1.5120]],

        [[ 0.7479],
         [ 0.8095],
         [-1.2800],
         [-1.4071]],

        [[ 1.7679],
         [-1.7466],
         [-0.9898],
         [-0.0154]],

        [[ 1.2572],
         [-0.0746],
         [-1.7554],
         [ 0.5165]]])
torch.Size([4, 4, 1])


In [51]:
p = torch.randn(4,4,3)
print(p)
print(p[2:4,1:3,1:2])

tensor([[[-0.9059,  0.4606,  0.7382],
         [ 0.0536,  0.0473, -0.1993],
         [ 0.7860, -1.1700,  1.0170],
         [ 0.7682,  0.1255,  1.3502]],

        [[-0.4832,  0.5291,  0.1849],
         [-0.4483, -0.5518,  0.7448],
         [-0.6352,  1.2675,  1.1176],
         [ 0.4980, -1.4012, -0.0718]],

        [[-0.9832, -0.1637,  2.4064],
         [ 0.6961,  0.7308, -1.0212],
         [-0.7064,  0.6007, -1.2924],
         [-0.6501, -1.6463,  1.3841]],

        [[-1.0277, -0.0186,  0.1944],
         [-0.7739, -0.5036,  1.6582],
         [-1.1014,  2.2239,  0.2768],
         [-0.7389, -0.0097, -0.1004]]])
tensor([[[ 0.7308],
         [ 0.6007]],

        [[-0.5036],
         [ 2.2239]]])


In [52]:
a = torch.ones(5)
b = a.numpy()
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [53]:
a = numpy.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [56]:
mat1 = torch.randn(2,3)
mat2 = torch.randn(3,4)
mat1mat2 = torch.mm(mat1, mat2)
print(mat1mat2)
print(mat1mat2.size())

tensor([[-0.6484, -0.0900, -1.1752,  0.6390],
        [ 1.4526,  1.9583, -0.0731,  0.6188]])
torch.Size([2, 4])


In [63]:
xx = torch.rand(2,3,4,3,6)
xx

tensor([[[[[7.5113e-01, 9.2840e-01, 2.5204e-01, 5.9310e-01, 8.6885e-01,
            1.5899e-01],
           [5.5664e-01, 2.5549e-01, 3.7906e-01, 5.8642e-01, 6.8040e-01,
            2.8356e-01],
           [7.6139e-01, 6.4728e-01, 9.5000e-01, 2.3498e-01, 5.1256e-01,
            7.3280e-01]],

          [[5.7801e-01, 3.9646e-01, 7.7179e-01, 8.7047e-02, 3.2175e-01,
            4.2005e-01],
           [7.9041e-01, 9.2271e-01, 4.0957e-01, 6.7327e-01, 5.4931e-01,
            7.2250e-01],
           [5.0407e-01, 8.6157e-01, 7.9494e-01, 2.0796e-02, 4.0827e-01,
            3.6775e-01]],

          [[7.3595e-01, 6.1878e-01, 4.9777e-01, 4.8359e-01, 8.4956e-01,
            6.1483e-01],
           [9.4933e-01, 8.3118e-01, 9.9256e-01, 8.2998e-01, 9.7759e-01,
            2.9485e-01],
           [8.1364e-02, 4.2587e-01, 4.8889e-01, 4.4939e-01, 7.6471e-01,
            6.3128e-01]],

          [[6.9726e-01, 8.8987e-02, 4.9105e-01, 6.0670e-01, 9.4923e-01,
            9.9811e-01],
           [6.7100e-01, 